### ISSUE TITLE
Could you show your results in MSD 2018?

### ISSUE THREAD

**Issue by huangmozhilv** [ORippler/MSD_2018#1]
Thank you for sharing the code. However, could you show your results in MSD 2018?

**Comment by ORippler** [comment]
Hi,

results are available at the [organizers website](http://medicaldecathlon.com/results.html).

Best,
ORippler

**Comment by huangmozhilv** [comment]
Hi ORippler,

Thank you so much. You are very generous to make the code public.

Happy new year,
Chao
